### ISSUE TITLE
Datapunkter er ens

### ISSUE THREAD

**Issue by bukkrog** [kpoppel/homeassistant-eforsyning#11]
Hej,

Har du før oplevet at datapunkterne er ens af dem der kom ind.?

![image](https://user-images.githubusercontent.com/91331889/134777213-9f69142e-7bf3-4aea-8631-49f285515d50.png)

**Comment by bukkrog** [comment]
![image](https://user-images.githubusercontent.com/91331889/134777264-f55d1466-16ac-4fd5-9d03-10292eba0211.png)

**Comment by kpoppel** [comment]
Version 0.5.0 henter data baseret på "daglig"-tallene nu.  Det fjerner en midling som eforsyning foretager når der spørges om data via "årsforespørgsel".
