### ISSUE TITLE
cant access data

### ISSUE THREAD

**Issue by PSfreak** [kpoppel/homeassistant-eforsyning#13]
I am not recieving any data to Home Assisent, i think i have done as described
I logging in whit the information from the supply company, is that the way to do it?

**Comment by kpoppel** [comment]
You need a user name and password. The same as when logging in usingt he browser.
Additionally you need the supplier ID.  Try to follow the instruction in the Readme file.
without the supplier ID, the calls to eforsyning's API does not know where to apply the user name and password and login will fail.

I updated the readme file too, as the description was not updated for a while.

**Comment by merrild4** [comment]
Same for me.
I am not recieving any data to Home Assisent,
I have User name  Password  and Supplier ID.
what am I doing wrong ?

**Comment by allanpersson** [comment]
I had same problem for a long time, what I did a couple of days ago and is working is:

First I login on my page and double checking my username and password is correct.

Second I right clicked ➡️ view source code in Vivaldi (Chrome) found the supplier ID and pasted those 3⃣ things into a fresh integration in config UI (re-downloaded the integration, made sure no active integration settings for this integration was present, restarted)

And for the first time I had luck 🤞

**Comment by kpoppel** [comment]
I updated the readme for the same purpose. If anyone knows of a better way to get that supplier Id I would like to know.

**Comment by kpoppel** [comment]
There does not seem to be more activity on this issue.  If you still have trouble after following the README, try and open another issue with full details on what you did, log files etc.
