### ISSUE TITLE
sensors unknown

### ISSUE THREAD

**Issue by hedevej41** [kpoppel/homeassistant-eforsyning#15]
All sensors is unknown. i follow the instruks

**Comment by kpoppel** [comment]
Hi. Please add the debugging lines to your config file and observe the extra information printed in the log file. Just letting me know it does not work is not enough to let me know what the problem is.

**Comment by hedevej41** [comment]
my logs says this  

This error originated from a custom integration.

Logger: custom_components.eforsyning
Source: custom_components/eforsyning/__init__.py:109
Integration: EForsyning
First occurred: 23:44:17 (1 occurrences)
Last logged: 23:44:17

Exception: <class 'KeyError'>

and the full log says this

2022-02-13 21:49:50 WARNING (SyncWorker_2) [custom_components.eforsyning] Exception: <class 'KeyError'>

**Comment by kpoppel** [comment]
Hi again

Did you enable the debugging information lines in the configuration yaml file?  I would expect some more output to help me figure out where in the plugin this comes from.
A KeyError could come from returned data from the API the plugin calls where something needed is not present.  And that could maybe come from e.g. a wrong login, or your local supplier not using this API yet.  I don't know just based on the above .-)

**Comment by kpoppel** [comment]
Closed as stale.  If the problem persists, please let me know.
