### ISSUE TITLE
Error when installing the integration

### ISSUE THREAD

**Issue by Behrendorff** [kpoppel/homeassistant-eforsyning#17]
Hi,

After copying the folder to Custom_components, I get this error:

![image](https://user-images.githubusercontent.com/47922574/158177257-0cc66223-6fd0-411d-8349-d20e42ec44bf.png)

Any idea what to do?

Thank you!

**Comment by kpoppel** [comment]
Du you have the Home Assistant server log file output for this?  A little searching reveals many sources of this type of error.
Which version of Home Assistant are you using?  Is this a new installation?  Did you installl using the HACS plugin (preferred)?

**Comment by Behrendorff** [comment]
I reinstalled it, and now it works! Thank you!

**Comment by kpoppel** [comment]
That is great. I hope you will be happy with the data.
