### ISSUE TITLE
More information on "Add Integration" step

### ISSUE THREAD

**Issue by jolsso** [kpoppel/homeassistant-eforsyning#2]
Hi
Can you please add some more information on the "Add Integration" step (After installation into HACS)?
E.g.
User Name = Forbrugernummer?
Password = Kode (4 cifre)?
Supplier id = ?
Thx for a (hopefully) great plugin.

**Comment by kpoppel** [comment]
Hi @jolsso .  I have improved the README file.  Thanks for pointing it out.  I just reused one from another plugin, (eloverblik), and never managed to document how to get the supplier id.  I hope it is clear enough for you to get it going.
