### ISSUE TITLE
Not starting on version 2022.7.1

### ISSUE THREAD

**Issue by jnxxx** [kpoppel/homeassistant-eforsyning#21]
After updating to 2022.7.1 (probably also 2022.7.0) the eforsyning integration did not start at my instance.

It seemed to be caused by this requirement in manifest.json: "requests==2.27.1"

According to [this](https://developers.home-assistant.io/docs/creating_integration_manifest/#custom-integration-requirements) requests should not be included as a requirement as it is already required by the Core.
I just removed it and left the array empty, then it is starting.

**Comment by kpoppel** [comment]
Thanks for the tip!

**Comment by mortalone** [comment]
i dont really understand what i have to edit to get it to work.

please explain in detail.

this is my manifest.json file content
`{
  "domain": "eforsyning",
  "name": "EForsyning",
  "version": "0.3.0",
  "config_flow": true,
  "documentation": "https://www.home-assistant.io/integrations/eforsyning",
  "issue_tracker": "https://github.com/kpoppel/homeassistant-eforsyning/issues",
  "requirements": [
    "requests==2.27.1"
  ],
  "ssdp": [],
  "zeroconf": [],
  "homekit": {},
  "dependencies": [],
  "codeowners": [
    "@kpoppel"
  ]
}`

and it lookes like other manifest.json file contents with no errors

**Comment by kpoppel** [comment]
I released v0.8.0 just now with this change incorporated.

**Comment by mortalone** [comment]
Nice. thank you
