### ISSUE TITLE
can not add eforsyning in integrations after install with hacs

### ISSUE THREAD

**Issue by hedevej41** [kpoppel/homeassistant-eforsyning#22]
min ha er rebooted efter instalation fra hacs. når jeg vil tilføje eforsyning i integrations får jeg følgende fejl

ha core version 2022.7.5

Error
Config flow could not be loaded: undefined

**Comment by kpoppel** [comment]
I released v0.8.0 just now with a change incorporated that solves at least one issue with the latest Home Assistant compatibility.
If this fixes it for you, please let me know and close the issue :-)

**Comment by hedevej41** [comment]
yes now it works and ha puls the data from eforsyning again
