### ISSUE TITLE
Get water usage from eforsyning

### ISSUE THREAD

**Issue by kassoren** [kpoppel/homeassistant-eforsyning#24]
Hey Again

I would love to be able to use this component for my "water supply" on eforsyning (Vand forsyning. Fjernvarme virker allerede helt perfekt.)

We talked about this function earlier, and I have tested a little bit. But I'm not able to get as much data as i want.

Seems to me that 2 of the 14 entities is receiving some information. The rest of them are blank. Which actually makes sense, for example your cooling of the water is not meassured for your "normal" water supply. This is mostly just m3 in and out.

xx_water_exp_end - Is receiving expected usage in m3
xx__water_end - Is receiving what you actually used in m3

(The 2 above entities are update like twice a week - I think)

The rest of the entities are not receiving anything.

It could be really cool if you were able to pull out some more data. 

An example from snippit on eforsyning for my water usage:
![Måned på et år](https://user-images.githubusercontent.com/99141498/182934203-01edfd2e-74e1-49e9-a6b0-1430cf085820.PNG)

and

for each day in a month:
![per day](https://user-images.githubusercontent.com/99141498/182934254-aeb1d85c-2fe5-4965-b21b-9739ce24989b.PNG)

I want to be able to integrate the date from "Målt" and "Forventet" on the picture 

I totally understand if this is too much to ask, because as i understand the intention for this was not the "water supply"-company :)

Have a great day

**Comment by kpoppel** [comment]
Hi @kassoren .  I don't think this would be a 'big' thing as it is the same data supplier.  At least in terms of interpreting the data rereturned.  If you don't mind I would need access to your water meter account to see what comes out of it.
If I can work it out, I should be able to make a checkbox in the configuration to switch "water mode" on and get  only the necessary sensors created.  That is a slightly bigger thing, but I can have a look.

**Comment by kassoren** [comment]
Thank you so much.. how do i text you in private?

cant remember your email :)

**Comment by kpoppel** [comment]
We can make a quick screen share. That seemed to work out nicely last time.  Then we don't have personal information lying around Github :-)

**Comment by kassoren** [comment]
Thats a plan

Give me 2 minutes to get ready

**Comment by kassoren** [comment]
Ready 

195703501008

**Comment by kpoppel** [comment]
Okay, so what is returned from eForsyning considering a water meter is this, when all the useless (as in: never changing throughout all data points) data is removed.  The snippet below is the same as the day shown in your image above:

```
"ForbrugsLinjer": {
  "TForbrugsLinje": [
 {
    "Afl_Nr": "1125331",   <- changes but has no information value
    "TilDatoStr": "15-07-2022", <- End date
    "STAflType": "0", <- is 30 or 0 - no information value
    "Lbnr_andet": "0", <- is 1 or 0, 1 when STAflType is 30 - no information value
    "TForbrugsTaellevaerk": [
     {
      "IndexNavn": "M3", <- Looks about right
      "Enhed_Txt": "m³",  <- Looks about right
      "Slut": "727", <- increasing number
      "Start": "727", <- increasing number = Slut the day before
      "Forbrug": "0" <- Slut-Start
     }],
    "Elek_mtype": "0", <- is 0 or 33 (don't know the connection) - no information value
    "Elek_MalNr": "", <- empty or 8 digit number - no information value
    "Fiktiv": "True", <- True or False - I don't know if the supplier guesses values. No value for HA
    "Aflas_kilde_text": "", <- empty or "aflæst af værket" (it can still be Fiktiv=true though) - no information value
    "ForventetAflaesningM3": "849", <- ever growing number
    "Lbnr_elek": "0", <- 0 or 1. Seems to be 1 when Aflas_kile_text is set - no information value
    "Mek_MalNr": "", <- empty or the same number as Elek_MalNr  - no information value
    "FraDatoStr": "14-07-2022", <- Start date, always TilDatoStr from the day before
    "Aflas_kilde_id": "0", <- 0 or 10. 10 when Aflas_kilde_text set  - no information value
    "Lbnr_mek": "0",<- 0 or 1.  1 when Aflas_kilde_text set  - no information value
    "ForventetForbrugFraRealiseredeGraddageFaktor": "0",  - no information value
    "AflType": "0", <- 0 or 30.  30 when Aflas_kilde_text set  - no information value
    "HaandTermnr": "", <- empty or same 8 digit number. - no information value
    "OprettetAfUdjaevningen": "True", <- True or False.  False when Aflas_kilde_text set  - no information value
    "Ejd_Aktivnr": "0", <- 0 or 1
   }
```

There are a few other lines which may or may not have value:
```
"IaltLinje": {
  "TilDatoStr": "05-08-2022",
  "SidsteAflNr": "1142018",
  "TForbrugsTaellevaerk": [
   {
    "Slut": "672", <- Matches numbers from January and March, makes no sense to me. (I would expect 734=653+81)
    "Start": "653", <-  Matches numbers from January 1st
    "Forbrug": "81"  <- This is the difference from Jan 1st to today's date.
   }],
  "FraDatoStr": "31-12-2021", <-  since date
  "AntForbrugsLinjer": "70",  <- Looks about right, matching the number of "aflæse af værket" lines
  "ForventetForbrugM3": "358",  <- Maybe this changes during the year?  Average consumption YTD extrapolated to FY
 },
```

Of 216 entries (January 1st to August 5th),  70 entries seem to be actual reads from the supply, the rest looks like they are fictive entries (OprettetAfUdjaevningen).  This corresponds to about every 3rd day as you also see. 38 are tagged as "Fiktiv:False". 74 entries have "Forbrug=1" and looks like every those are 3rd day on average.  These entries have fiktiv both true or false, so there's that.

Numbers matching the pictures above:
727 m3 is reached 2022-07-10, last seen 2022-07-19 (this date "aflæst af værket")
849 m3 is expected 2022-07-15

So with this analysis I think the only valuable information in terms of HomeAssistant would be:
- At "TilDatoStr" extract "Start", "Slut", "Forbrug" "ForventetAflasningM3", IaltLinje.TforbrugsTaellevaerk.Forbrug, and IaltLinje.ForventetForbrug (6 sensors)
- The module should not create the remaining sensors from the regional heating - they mean nothing for water readouts

To collect data monthly and so on, look into [Statistics sensors](https://www.home-assistant.io/integrations/statistics/)
There is also a question about InfluxFB for long term data history and the recorder (SQLite) [here](https://community.home-assistant.io/t/questions-about-recorder-statistics-influxdb/386386/4).  If you use the SQLite (default) recorder it purges data after default 10 days ([Check this](https://www.home-assistant.io/integrations/recorder/))

I'll get back on this issue when I have it in the code.

**Comment by kpoppel** [comment]
And this is the result:
![image](https://user-images.githubusercontent.com/4174578/183267524-607e01dc-c8e2-4033-a3f8-c495d02d87bc.png)

In the end I added sensors for start, end, expected end, water used and expected used, calculation of the expected to-date used water, actual used water, and expected full year used.

Code is pushed ot main in a bit.  You will need to try it out for a few days (water needs to flow :-) ) and let me know how it works out.
If all is okay I will publish the module for all to update to.

Edit:
Before adding this version, please remove the one you have added for the water login first.  I have added a checkbox to activate "water-mode" and just create the sensors listed above.

**Comment by kassoren** [comment]
That is awesome! and sorry for the slow response.. I will test it out asap.. 

Thanks again :)

**Comment by kassoren** [comment]
Oh, and will I have to re-download the eforsyning integration from HACS to test this out?

Got it.. Found the update named "main".. Just misunderstod what you said above.. Thanks

Update:
Got it working.. Testing.. I'll be back :)

**Comment by kpoppel** [comment]
As a special feature - I will commit an update where all the fetched data is available as attributes on all sensors.  This enables ApexCharts to make graphs like these:
![image](https://user-images.githubusercontent.com/4174578/183292754-108db2d7-fb0c-4f94-9e85-57a0f2363993.png)

![image](https://user-images.githubusercontent.com/4174578/183292800-3a216d96-1d16-416a-b120-0ba8af494a43.png)

... Just need to make the heating data pickup work again before I do that :-)

**Comment by kassoren** [comment]
That is Nice 👍💪

**Comment by kpoppel** [comment]
When you feel like it - pull the main branch again and try some of these apexCharts.
Hopefully your regional heating data will just keep on working like always, only now with attribute data.

```
type: custom:apexcharts-card
graph_span: 365d
span:
  end: day
header:
  show: true
  title: Varme - kWh totalforbrug
  show_states: true
  colorize_states: true
all_series_config:
  show:
    legend_value: false
    datalabels: false
    extremas: true
    in_brush: true
  float_precision: 0
  type: area
  invert: false
series:
  - entity: sensor.eforsyning_energy_end
    type: area
    data_generator: |
      return entity.attributes.data.map((start, index) => {
        return [new Date(start["DateFrom"]).getTime(), entity.attributes.data[index]["kWh-End"]];
      });
  - entity: sensor.eforsyning_energy_exp_end
    type: area
    data_generator: |
      return entity.attributes.data.map((start, index) => {
        return [new Date(start["DateFrom"]).getTime(), entity.attributes.data[index]["kWh-ExpEnd"]];
      });
```

```
type: custom:apexcharts-card
graph_span: 365d
span:
  end: day
header:
  show: true
  title: Varme - kWh forbrug
  show_states: true
  colorize_states: true
all_series_config:
  show:
    legend_value: false
    datalabels: false
    extremas: true
    in_brush: true
  float_precision: 3
  type: area
  invert: false
series:
  - entity: sensor.eforsyning_energy_used
    type: area
    data_generator: |
      return entity.attributes.data.map((start, index) => {
        return [new Date(start["DateFrom"]).getTime(), entity.attributes.data[index]["kWh-Used"]];
      });
  - entity: sensor.eforsyning_energy_exp_used
    type: area
    data_generator: |
      return entity.attributes.data.map((start, index) => {
        return [new Date(start["DateFrom"]).getTime(), entity.attributes.data[index]["kWh-ExpUsed"]];
      });
```

```
type: custom:apexcharts-card
graph_span: 365d
span:
  end: day
header:
  show: true
  title: Varme - M3 forbrug
  show_states: true
  colorize_states: true
all_series_config:
  show:
    legend_value: false
    datalabels: false
    extremas: true
    in_brush: true
  float_precision: 3
  type: area
  invert: false
series:
  - entity: sensor.eforsyning_water_end
    type: area
    data_generator: |
      return entity.attributes.data.map((start, index) => {
        return [new Date(start["DateFrom"]).getTime(), entity.attributes.data[index]["M3-Used"]];
      });
  - entity: sensor.eforsyning_water_exp_end
    type: area
    data_generator: |
      return entity.attributes.data.map((start, index) => {
        return [new Date(start["DateFrom"]).getTime(), entity.attributes.data[index]["M3-ExpUsed"]];
      });
```

```
type: custom:apexcharts-card
graph_span: 365d
span:
  end: day
header:
  show: true
  title: Varme - M3 totalforbrug
  show_states: true
  colorize_states: true
all_series_config:
  show:
    legend_value: false
    datalabels: false
    extremas: true
    in_brush: true
  float_precision: 3
  type: area
  invert: false
series:
  - entity: sensor.eforsyning_energy_end
    type: area
    data_generator: |
      return entity.attributes.data.map((start, index) => {
        return [new Date(start["DateFrom"]).getTime(), entity.attributes.data[index]["M3-End"]];
      });
  - entity: sensor.eforsyning_energy_exp_end
    type: area
    data_generator: |
      return entity.attributes.data.map((start, index) => {
        return [new Date(start["DateFrom"]).getTime(), entity.attributes.data[index]["M3-ExpEnd"]];
      });
```
```
type: custom:apexcharts-card
graph_span: 365d
span:
  end: day
header:
  show: true
  title: Varme - kWh forbrug ENG2 + TV2
  show_states: true
  colorize_states: true
all_series_config:
  show:
    legend_value: false
    datalabels: false
    extremas: true
    in_brush: true
  float_precision: 3
  type: area
  invert: false
series:
  - entity: sensor.eforsyning_energy_used
    type: area
    data_generator: |
      return entity.attributes.data.map((start, index) => {
        return [new Date(start["DateFrom"]).getTime(), entity.attributes.data[index]["kWh-ENG2-End"]];
      });
  - entity: sensor.eforsyning_energy_exp_used
    type: area
    data_generator: |
      return entity.attributes.data.map((start, index) => {
        return [new Date(start["DateFrom"]).getTime(), entity.attributes.data[index]["kWh-TV2-End"]];
      });
```

**Comment by kassoren** [comment]
So just to be sure, can i now use the “main” Update again? The one called main or the one called 0.9.1?

thanks

**Comment by kpoppel** [comment]
Right now all the new stuff is in "main".  If you find no issues, I will make the release properly (v.0.10.0).

**Comment by kpoppel** [comment]
I just found out that I could make the release v0.10.0 as 'pre-release' and find it in HACS by checking the "Show Beta Releases" switch on the integration.  It is now available in HACS:

![image](https://user-images.githubusercontent.com/4174578/183759501-794d7a57-63d7-4665-b895-fb304967f7ea.png)

**Comment by kassoren** [comment]
I'll test it out :)

**Comment by Bluhme1** [comment]
Looks very good. Very impressed by the amount af data to extract. And loving the Apex charts.
Just a question. Could you explain the meaning af kwh_ENG2 and kwh_TV2. The rest should be self-explanatory.
Thanks

**Comment by kpoppel** [comment]
What I can see in the data is that ENG1 and M3 fields is the data we are shown in the web-app.  The ENG2 and TV2 is also in kWh units, but no explanation is given on what they are.  I someone figures this out I could give them a better name.
 So right now, they are just for 'fun'.

**Comment by kpoppel** [comment]
The feature seems stable except for #25 now bothering everybody.
