### ISSUE TITLE
Fejl ved installation

### ISSUE THREAD

**Issue by frajoc** [kpoppel/homeassistant-eforsyning#31]
Hej
Først installering med HACS
Genstart som skrevet
Installering med integration, virker også.
Taster login/pass osv ind og gemmer det.
Det godkendes og er en succes.
Dog viser EForsyning nu fejl: Retrying setup: list index out of range
Og der laves ingen sensor osv.
Virker fint med ver. 0.11.3, dog ikke på ver. 1.0.0 / 1.0.1
## Log file output
Follow the guideline in the README.md file and post the result here. Make sure to clean the information from account information.

**Comment by Sdahl1234** [comment]
Opdateret til 1.0.1 og får også index out of range.

Logger: custom_components.eforsyning.coordinator
Source: custom_components/eforsyning/coordinator.py:55
Integration: EForsyning ([documentation](https://github.com/kpoppel/homeassistant-eforsyning), [issues](https://github.com/kpoppel/homeassistant-eforsyning/issues))
First occurred: 11.59.53 (7 occurrences)
Last logged: 12.03.58

Unexpected error fetching eForsyning data: list index out of range
Traceback (most recent call last):
  File "/config/custom_components/eforsyning/coordinator.py", line 53, in _async_update_data
    data = await self.hass.async_add_executor_job(self.api.get_latest)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 362, in get_latest
    billing_result = self._parse_result_billing(billing_data)
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 761, in _parse_result_billing
    metering_data['amount-remaining'] = self._stof(result[19]['ialt'])
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/eforsyning/coordinator.py", line 55, in _async_update_data
    raise ConfigEntryNotReady from error
homeassistant.exceptions.ConfigEntryNotReady: list index out of range

**Comment by kpoppel** [comment]
Det er så de nye data vedr. varmeregnskab. Jeres ser så ikke ud ligesom mit. 😒 Kan jeg få et debug output, så jeg kan se hvordan det ellers kan se ud?

Jeg påtænker så at tjekke for om data ligner det jeg har set indtil videre, og ellers have en tom sensor for resten.

**Comment by kpoppel** [comment]
v1.0.2 skulle gerne løse denne.

**Comment by kpoppel** [comment]
Prøv https://github.com/kpoppel/homeassistant-eforsyning/releases/tag/v1.0.4 . Denne version skulle gerne kunne parse varmeopgørelsen lidt mere præcist.

**Comment by Sdahl1234** [comment]
Jeg kan bekræfte at 1.0.4 virker hos mig. 
Nice work..
