### ISSUE TITLE
Getting failed login

### ISSUE THREAD

**Issue by JonasKristiansen** [kpoppel/homeassistant-eforsyning#37]
Hi, 

When trying to configure the Eforsyning I always get "Login failed. Bye". I can login on the Eforsyning portal without issues with the same credentials. 

With debug activated I get the following in the log:

<img width="1226" alt="Skærmbillede 2022-10-03 kl  20 15 49" src="https://user-images.githubusercontent.com/59250377/193650130-7eced84d-71e6-4d0b-8d71-e74e20a59065.png">

Hope you are able to help. Thank you :-)

**Comment by kpoppel** [comment]
It seems you do have the correct credentials, which in turn gives you a login token.
The next step which fails is using this token to perform the actual login on the API.  This happens [here](https://github.com/kpoppel/homeassistant-eforsyning/blob/7a7c29a40ab118aad7364e697654a97ae8ac35a8/custom_components/eforsyning/pyeforsyning/eforsyning.py#L301)

What you can do from here is not to add a line like this:
```_LOGGER.debug(f"Login result: {result_json}")``` after line 310 in that file.

The status returned from your specific login may be different from other's perhaps.  Or the token is no good.  In that case I would need to look into more detail on the network traffic.  We can do this either by screensharing or if I can 'borrow' your login, like others have done.  But try to see what the response is first, and post this.

**Comment by JonasKristiansen** [comment]
Hi, 

Thank you for the quick response. I have added the line and now get the following error in the log: 

<img width="1241" alt="Skærmbillede 2022-10-04 kl  19 39 28" src="https://user-images.githubusercontent.com/59250377/193888751-f967da54-da8c-4843-bf35-708322c67bc7.png">

I can send the credentials to you - I guess that would be the easiest way for you to debug the issue?

Thank you for the assistance!

**Comment by smulle48** [comment]
Jeg har samme problem

**Comment by kpoppel** [comment]
Ok, så er noget anderledes hos Jer.  Jeg har en mailadresse her: kpoppel.at.github@gmail.com hvis man vil sende login til mig, så ser jeg på det.  Jeg kan ikke reproducere det på mit eget login desværre.

**Comment by smulle48** [comment]
> Ok, så er noget anderledes hos Jer. Jeg har en mailadresse her: [kpoppel.at.github@gmail.com](mailto:kpoppel.at.github@gmail.com) hvis man vil sende login til mig, så ser jeg på det. Jeg kan ikke reproducere det på mit eget login desværre.

Jeg fik det til at virke.

Jeg har mulighed for at logge ind både med kundenummer og pinkode, samt email adresse og kode, men det er kun kundenummer og den 4 cifret pinkode der virker her hos mig med dette plugin :)

**Comment by kpoppel** [comment]
Ok, det er måske også forklaringen på @JonasKristiansen ?  Integrationen benytter sig af kundenummer og pinkode som adgangsvej.  Jeg kan se i netværkstrafikken, at email-login bruger nogle andre kald.  Jeg antager at alle der vil, kan bruge kundenummer+pin, indtil en feature-request kommer på banen for email-login, da det her kun er et fritidsprojekt.

Jeg vil opdatere dokumentationen på dette punkt så det bliver tydeligt/ere, at der er den type login.

@JonasKristiansen - prøv venligst med kundenr+pin.

https://github.com/kpoppel/homeassistant-eforsyning/commit/7d3d23a36e04f0864d070629b279ae8811be839c

**Comment by kpoppel** [comment]
Closing as inactive.  Please re-open if this problem persists.
