### ISSUE TITLE
[Request] Add year total water return temperature

### ISSUE THREAD

**Issue by Sdahl1234** [kpoppel/homeassistant-eforsyning#38]
If it is possible. 

My supplier gives me a penalty if my return temperature is above 37 degrees.

**Comment by kpoppel** [comment]
How should this work? It it a number we can fetch, or some aversge/max to be calculated.

**Comment by Sdahl1234** [comment]
I dont know how you fetch the data, but I can see it if I select the year series on eforsynings webpage. There is also one for each month.


![image](https://user-images.githubusercontent.com/80645006/197297084-79a34b32-f061-4ae0-9bd3-37a8a3448b82.png)
![image](https://user-images.githubusercontent.com/80645006/197297755-645daf4f-cd5c-44a1-a44b-0a8c1e0b36b6.png)

**Comment by Sdahl1234** [comment]
I took a quick look in devtools in the browser. 
One of the getforbrug has this return value for 2022

{
 "ForbrugsLinjer": {
  "AktuelLinjeNr": "0",
  "AntLinjer": "1",
  "TForbrugsLinje": [
   {
    "TempRetur": "35,2977630880009",    <---- this value is the year total water return temperature
    "Afl_Nr": "XXXXXXX",
    "AntTaellevaerker": "5",
    "TilDatoStr": "20-10-2022",
    "Art": "0",
    "STAflType": "60",
    "Lbnr_andet": "3",
    "Mell_AflNr": "0",
    "TForbrugsTaellevaerk": [
     {
      "IndexNavn": "ENG1",
      "Enhed_Txt": "MWh",
      "Korrig": "0,000",
      "Beskrivelse": "Energi",
      "Enhed": "7",
      "Faktor": "1",
      "Slut": "131,879",
      "Start": "120,735",
      "Format": "######0.000",
      "Forbrug": "11,144"
     },{
      "IndexNavn": "M3",
      "Enhed_Txt": "m³",
      "Korrig": "0,00",
      "Beskrivelse": "volumen",
      "Enhed": "1",
      "Faktor": "1",
      "Slut": "4590,50",
      "Start": "4251,64",
      "Format": "####0.00",
      "Forbrug": "338,86"
     },{
      "IndexNavn": "TIME_",
      "Enhed_Txt": "Timer",
      "Korrig": "0",
      "Beskrivelse": "timetæller",
      "Enhed": "20",
      "Faktor": "1",
      "Slut": "50727",
      "Start": "43767",
      "Format": "#####0.",
      "Forbrug": "6960"
     },{
      "IndexNavn": "ENG2",
      "Enhed_Txt": "M3*TF",
      "Korrig": "0,00",
      "Beskrivelse": "Gns frem",
      "Enhed": "10",
      "Faktor": "1",
      "Slut": "308107,00",
      "Start": "286360,00",
      "Format": "####0.00",
      "Forbrug": "21747,00"
     },{
      "IndexNavn": "TV2",
      "Enhed_Txt": "M3*TF",
      "Korrig": "0,00",
      "Beskrivelse": "Gns retur",
      "Enhed": "10",
      "Faktor": "1",
      "Slut": "192124,00",
      "Start": "180163,00",
      "Format": "####0.00",
      "Forbrug": "11961,00"
     }],
    "Elek_mtype": "30",
    "LinieStatistik": {
     "DiffProc": "0",
     "RefEnhed": "0",
     "RefTilDatoStr": "30-12-1899",
     "Difference": "0",
     "Forventet": "0",
     "Reference": "0",
     "RefFraDatoStr": "30-12-1899",
     "TvNavn": ""
    },
    "Elek_MalNr": "XXXXXXX",
    "Fiktiv": "False",
    "Taellevaerker": {
     "Text": "ENG1|M3|TIME_|ENG2|TV2|"
    },
    "VarKorrigeret": "False",
    "ForventetAflaesningENG1": "0",
    "Aflas_kilde_text": "aflæst af værket",
    "Kommentar": "",
    "ForventetAflaesningM3": "0",
    "StartaflFejlkode": "0",
    "Alfasog": "80",
    "Afkoling": "28,2779909249106",
    "Afl_Metode": "0",
    "Lbnr_elek": "3",
    "Korrig_afl_nr": "0",
    "Mek_MalNr": "XXXXXXX",
    "AarsMaerke": "0",
    "FraDatoStr": "03-01-2022",
    "Afl_Tekst": "",
    "ForventetForbrugENG1": "0",
    "Forv_Retur": "37",
    "Tempfrem": "64,176946231482",
    "Aflas_kilde_id": "10",
    "Lbnr_mek": "2",
    "ForventetForbrugFraRealiseredeGraddageFaktor": "0",
    "Fakturanr": "0",
    "Text": "ENG1|M3|TIME_|ENG2|TV2|",
    "Pris": "0",
    "Fejlkode": "0",
    "AktuelTaellevaerksNr": "0",
    "AflType": "30",
    "JournalNummer": "0",
    "HaandTermnr": "XXXXXXX",
    "I_Alt_Kr": "0",
    "NeutraltOmraadeOvre": "0",
    "OprettetAfUdjaevningen": "False",
    "EkskluderetMedFilter": "False",
    "Ejd_Aktivnr": "5",
    "ForventetForbrugM3": "0",
    "NeutraltOmraadeNedre": "0"
   }],
  "Text": "0|",
  "Pris": "0"
 },
 "Kategorier": "",
 "ITP": "0",
 "AarSlut": "31-12-2022",
 "Adresse": "",
 "IaltLinje": {
  "TempRetur": "35,2977630880009",  <---- this value is the year total water return temperature
  "AntTaellevaerker": "5",
  "TilDatoStr": "20-10-2022",
  "SidsteAflNr": "XXXXXXX",
  "TForbrugsTaellevaerk": [
   {
    "IndexNavn": "ENG1",
    "Enhed_Txt": "MWh",
    "Korrig": "0,000",
    "Beskrivelse": "Energi",
    "Enhed": "7",
    "Faktor": "1",
    "Slut": "131,879",
    "Start": "120,735",
    "Format": "######0.000",
    "Forbrug": "11,144"
   },{
    "IndexNavn": "M3",
    "Enhed_Txt": "m³",
    "Korrig": "0,00",
    "Beskrivelse": "volumen",
    "Enhed": "1",
    "Faktor": "1",
    "Slut": "4590,50",
    "Start": "4251,64",
    "Format": "####0.00",
    "Forbrug": "338,86"
   },{
    "IndexNavn": "TIME_",
    "Enhed_Txt": "Timer",
    "Korrig": "0",
    "Beskrivelse": "timetæller",
    "Enhed": "20",
    "Faktor": "1",
    "Slut": "50727",
    "Start": "43767",
    "Format": "#####0.",
    "Forbrug": "6960"
   },{
    "IndexNavn": "ENG2",
    "Enhed_Txt": "M3*TF",
    "Korrig": "0,00",
    "Beskrivelse": "Gns frem",
    "Enhed": "10",
    "Faktor": "1",
    "Slut": "308107,00",
    "Start": "286360,00",
    "Format": "####0.00",
    "Forbrug": "21747,00"
   },{
    "IndexNavn": "TV2",
    "Enhed_Txt": "M3*TF",
    "Korrig": "0,00",
    "Beskrivelse": "Gns retur",
    "Enhed": "10",
    "Faktor": "1",
    "Slut": "192124,00",
    "Start": "180163,00",
    "Format": "####0.00",
    "Forbrug": "11961,00"
   }],
  "LinieStatistik": {
   "DiffProc": "0",
   "RefEnhed": "0",
   "RefTilDatoStr": "30-12-1899",
   "Difference": "0",
   "Forventet": "0",
   "Reference": "0",
   "RefFraDatoStr": "30-12-1899",
   "TvNavn": ""
  },
  "Taellevaerker": {
   "Text": "ENG1|M3|TIME_|ENG2|TV2|"
  },
  "VarKorrigeret": "False",
  "Afkoling": "28,2779909249106",
  "FraDatoStr": "03-01-2022",
  "ForventetForbrugENG1": "0",
  "Forv_Retur": "37",
  "AntForbrugsLinjer": "1",
  "Tempfrem": "64,176946231482",
  "ForventetForbrugFraRealiseredeGraddageFaktor": "0",
  "AntEjendomme": "0",
  "AntInstallationer": "0",
  "Text": "ENG1|M3|TIME_|ENG2|TV2|",
  "Pris": "0",
  "AktuelTaellevaerksNr": "0",
  "I_Alt_Kr": "0",
  "NeutraltOmraadeOvre": "0",
  "ForventetForbrugM3": "0",
  "NeutraltOmraadeNedre": "0"
 },
 "InstDato": "27638",
 "InstAdrUds": "False",
 "IHusNr": "0",
 "MaalAflFysNr": "",
 "IVejNr": "0",
 "Afk_Metode": "0",
 "ILitraer": "",
 "AarStart": "01-01-2022",
 "PrognEng1Uds": "False",
 "Vv_Proc": "0",
 "PrognM3Uds": "False",
 "Text": "",
 "LbNr": "1",
 "Afk_Graense2": "0",
 "Afk_Graense1": "0"
}

**Comment by kpoppel** [comment]
Okay.  So I see  "TempRetur" value.  This value is translated into the sensor `sensor.eforsyning_water_temperature_exp_return` 
It is the purple one here on my view:
![image](https://user-images.githubusercontent.com/4174578/197305595-f65d8802-a9f9-4be2-81f0-5ae63f82aff9.png)

So - as long as `sensor.eforsyning_water_temperature_return` is below everything should be fine.  If above - sure thing an adjustment of the system is in order.  Also if the water consumption.

Additionally two other graphs of actual vs. expected for the energy and water consumption are available:
![image](https://user-images.githubusercontent.com/4174578/197305843-82647c42-7fe7-4518-b6cf-d58b21e1e94c.png)

**Comment by Sdahl1234** [comment]
Yes, but the value of the sensor is the value of the latest day, not the total of the year.
TempReturn from my example is the total of the year.
What i would like is a sensor sensor.eforsyning_water_temperature_return_year. The value would be for the current year and attributes for earlier years.
Just like the sensor.eforsyning_water_temperature_return. Value from current day, attributes with values from all days.

**Comment by kpoppel** [comment]
Ah, I understand.  Sure that should be possible.  I'll look into this.

**Comment by Sdahl1234** [comment]
Works. This is cool. Nice job Mr. @kpoppel

**Comment by Bluhme1** [comment]
I get the new sensor but the value is 0.0. This is obviously not the case. I had my meter installed in March this year. So maybe it’s to early to close the subject

**Comment by kpoppel** [comment]
Try to take a look at the network traffic in the proper website. Does it fetch an average return temperature in a JSON field called IaltLinje? Because that is what I am parsing 😊

**Comment by Bluhme1** [comment]
Strange. I only get data previous years - from the period 2004 to 2010. Please see:

state_class: measurement
data: 
- DateFrom: 23-04-2004
  DateTo: 18-04-2005
  kWh-Used: 29,484
  kWh-ExpUsed: 125,574
  M3-Used: 885,21
  M3-ExpUsed: 4506,68
  Temp-Forward: 0
  Temp-Return: 0
  Temp-ExpReturn: 0
  Temp-Cooling: 28.64
- DateFrom: 18-04-2005
  DateTo: 27-04-2006
  kWh-Used: 32,744
  kWh-ExpUsed: 130,784
  M3-Used: 1090,24
  M3-ExpUsed: 4693,66
  Temp-Forward: 0
  Temp-Return: 0
  Temp-ExpReturn: 0
  Temp-Cooling: 25.825
- DateFrom: 27-04-2006
  DateTo: 25-04-2007
  kWh-Used: 27,057
  kWh-ExpUsed: 126,7
  M3-Used: 838,49
  M3-ExpUsed: 4547,12
  Temp-Forward: 0
  Temp-Return: 0
  Temp-ExpReturn: 0
  Temp-Cooling: 27.747
- DateFrom: 25-04-2007
  DateTo: 18-12-2007
  kWh-Used: 13,935
  kWh-ExpUsed: 58,462
  M3-Used: 464,40
  M3-ExpUsed: 2098,12
  Temp-Forward: 0
  Temp-Return: 0
  Temp-ExpReturn: 42
  Temp-Cooling: 25.801
- DateFrom: 18-12-2007
  DateTo: 30-12-2008
  kWh-Used: 30,566
  kWh-ExpUsed: 66,752
  M3-Used: 974,87
  M3-ExpUsed: 2395,66
  Temp-Forward: 0
  Temp-Return: 0
  Temp-ExpReturn: 42
  Temp-Cooling: 26.96
- DateFrom: 30-12-2008
  DateTo: 04-01-2010
  kWh-Used: 30,806
  kWh-ExpUsed: '65'
  M3-Used: 1065,20
  M3-ExpUsed: 2332,76
  Temp-Forward: 0
  Temp-Return: 0
  Temp-ExpReturn: 42
  Temp-Cooling: 24.867

unit_of_measurement: °C
device_class: temperature
icon: mdi:thermometer
friendly_name: EForsyning Water Temperature return year-to-date

**Comment by Bluhme1** [comment]
I havde consulted the debug content and get the following when searching for IaltLinje in the actual year. As you can see the TempRetur is "0". 

"Pris": "0"
},
"Kategorier": "",
"ITP": "0",
"AarSlut": "31-10-2022",
"Adresse": "",
"IaltLinje": {
"TempRetur": "0",
"AntTaellevaerker": "2",
"TilDatoStr": "28-10-2022",
"SidsteAflNr": "6848365",
"TForbrugsTaellevaerk": [
{
"IndexNavn": "M3",
"Enhed_Txt": "M3",
"Korrig": "0,000",
"Beskrivelse": "m3",
"Enhed": "1",
"Faktor": "1",
"Slut": "195,867",
"Start": "195,681",
"Format": "####0.000",
"Forbrug": "63,992"
},{

**Comment by kpoppel** [comment]
Okay the 2004 and forward data is a bug. Reopenimg the issue.. Do not go forward from first year but backwards from current year. My bad.
As for your 2022 data that seems as it should be for now.... As in, you apparently do not have this record from your supplier.

**Comment by kpoppel** [comment]
The bugfix also fixing #40 should handle this one as well.

**Comment by Bluhme1** [comment]
Works perfectly. Thank you (again)

**Comment by kpoppel** [comment]
Great. I'll close this issue then 😊
