### ISSUE TITLE
Current Price (Not an issue, just a suggestion)

### ISSUE THREAD

**Issue by JudgeFredd** [kpoppel/homeassistant-eforsyning#39]
Hi sorry if i'm posting incorrectly or otherwise stamping on somebodys feet.. ;-)

I was wondering if the api can pull the current price, i have recently change to a flexibel payment rate, which means the price pr. W. changes hourly. 
If i go to eloverblik.dk and choses to dl my data, i can choose "price data" and it seems like this covers the hourly price, not sure if it current or for yesterday though.. (my supplier is Norlys).

If it can, it would of course be nothing less than fantastic if you could integrate the data.. ;-)

I have attached an example og the excel data i can dowload.
[Price.csv](https://github.com/kpoppel/homeassistant-eforsyning/files/9888009/Price.csv)

**Comment by kpoppel** [comment]
I think you may ask the right question in the wrong place.  This integration is made for retrieving data from eForsyning which delivers water and regional heating.  From your question I read electricity supply, which is another integration.

If you want hourly price data then the integration [Nordpool](https://github.com/custom-components/nordpool) is what you need, or the Energi Data Service one which is basically the same but with further data from some prediction logic.

**Comment by JudgeFredd** [comment]
Yeah, sorry about that. I am using your "eforsyning" addon, wich is very great. :-)
I'm alsousing an addon called "eloverblik" and somehow they got switched up in my brain.. ;-)
The other addon as it turned out, already supports getting current elecrticity price, so thats great asswell.. ;-)
