### ISSUE TITLE
Please use releases

### ISSUE THREAD

**Issue by jolsso** [kpoppel/homeassistant-eforsyning#4]
```
Versions#

If the repository uses GitHub releases, the tagname from the latest release is used to set the remote version. Just publishing tags is not enough, you need to publish releases.

If the repository does not use tags, the 7 first characters of the last commit will be used.
```

https://hacs.xyz/docs/publish/start#versions
https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository

This would allow to roll back if there are any problems in a new release.

**Comment by jolsso** [comment]
I'm a bit unsure how this related to manifest.json version.

**Comment by kpoppel** [comment]
I think they are different.  HomeAssistant reads the manifest.json to see which dependencies needs to be installed for instance. Hacs is basically a git-frontend, and I would be surprised if that infrastructure goes about looking at individual files in the repositories.

**Comment by kpoppel** [comment]
I made Git release 0.3.0 with the latest changes.  I hope this will work as expected.
