### ISSUE TITLE
Getting data shown in HA grouped/aggregated by month

### ISSUE THREAD

**Issue by danededane** [kpoppel/homeassistant-eforsyning#41]
Hi kpoppel , 

Thanks for this awesome HA integration! 

This is not really an issue but I couldn't create a feature request and didn't know how to ask you in any other way.
I would like to be able to group the data on months which seems to be a little difficult in HA and made me think it would be easier to go and handle with a view in mariadb like I've done before.

Unfortunately the sensor data is stored as JSON in state_attributes I then have to use json_table to read the json into columns. 
Each of the many eforsyning sensors have its own state_attributes so I guess in the end I would have to join these many "virtual" json tables ... which I tried ...

```
SELECT JT_E_USED.date, 
JT_E_USED.energy_used, 
JT_E_EXP_USED.energy_exp_used, 
JT_WT_EXP_RETURN.water_exp_return, 
JT_WT_FORWARD.water_forward, 
JT_WT_RETURN.water_return, 
JT_WT_COOLING.water_cooling
FROM (
		SELECT shared_attrs FROM homeassistant.states as S
		INNER JOIN homeassistant.state_attributes as A ON S.attributes_id=A.attributes_id
		where entity_id like 'sensor.eforsyning_energy_used'
		order by last_updated desc
		limit 1
) as E_USED, 
(
		SELECT shared_attrs FROM homeassistant.states as S
		INNER JOIN homeassistant.state_attributes as A ON S.attributes_id=A.attributes_id
		where entity_id like 'sensor.eforsyning_energy_exp_used'
		order by last_updated desc
		limit 1
) as E_EXP_USED, 
(
		SELECT shared_attrs FROM homeassistant.states as S
		INNER JOIN homeassistant.state_attributes as A ON S.attributes_id=A.attributes_id
		where entity_id like 'sensor.eforsyning_water_temperature_exp_return'
		order by last_updated desc
		limit 1
) as WT_EXP_RETURN, 
(
		SELECT shared_attrs FROM homeassistant.states as S
		INNER JOIN homeassistant.state_attributes as A ON S.attributes_id=A.attributes_id
		where entity_id like 'sensor.eforsyning_water_temperature_return'
		order by last_updated desc
		limit 1
) as WT_RETURN, 
(
		SELECT shared_attrs FROM homeassistant.states as S
		INNER JOIN homeassistant.state_attributes as A ON S.attributes_id=A.attributes_id
		where entity_id like 'sensor.eforsyning_water_temperature_forward'
		order by last_updated desc
		limit 1
) as WT_FORWARD, 
(
		SELECT shared_attrs FROM homeassistant.states as S
		INNER JOIN homeassistant.state_attributes as A ON S.attributes_id=A.attributes_id
		where entity_id like 'sensor.eforsyning_water_temperature_cooling'
		order by last_updated desc
		limit 1
) as WT_COOLING, 
json_table(E_USED.shared_attrs, '$.data[*]' 
  columns(
    date date path '$.date',
    energy_used decimal(6,3) path '$.value'
  )
) as JT_E_USED
INNER JOIN
json_table(E_EXP_USED.shared_attrs, '$.data[*]' 
  columns(
    date date path '$.date',
    energy_exp_used decimal(6,3) path '$.value'
  )
) as JT_E_EXP_USED
ON JT_E_USED.date=JT_E_EXP_USED.date
INNER JOIN
json_table(WT_EXP_RETURN.shared_attrs, '$.data[*]' 
  columns(
    date date path '$.date',
    water_exp_return decimal(6,3) path '$.value'
  )
) as JT_WT_EXP_RETURN
ON JT_E_USED.date=JT_WT_EXP_RETURN.date
INNER JOIN
json_table(WT_RETURN.shared_attrs, '$.data[*]' 
  columns(
    date date path '$.date',
    water_return decimal(6,3) path '$.value'
  )
) as JT_WT_RETURN
ON JT_E_USED.date=JT_WT_RETURN.date
INNER JOIN
json_table(WT_FORWARD.shared_attrs, '$.data[*]' 
  columns(
    date date path '$.date',
    water_forward decimal(6,3) path '$.value'
  )
) as JT_WT_FORWARD
ON JT_E_USED.date=JT_WT_FORWARD.date
INNER JOIN
json_table(WT_COOLING.shared_attrs, '$.data[*]' 
  columns(
    date date path '$.date',
    water_cooling decimal(6,3) path '$.value'
  )
) as JT_WT_COOLING
ON JT_E_USED.date=JT_WT_COOLING.date
```

It gets something that looks like this:

![image](https://user-images.githubusercontent.com/9024493/202421264-3ef606bc-ab3d-4717-b0da-1cd1a05eb16a.png)

After creating this it made me think... "this is not the way"...

Do you have any other ideas?
Maybe extracting some parts of your code and inserting the data directly?
Or do you know a magic way to get HA to group the data by month?

**Comment by fuglphoenix** [comment]
you can do it with apexcharts. The important part is the **group by** in the series-section...

```
type: custom:apexcharts-card
graph_span: 365d
update_interval: 1d
span:
  end: day
header:
  show: true
  title: Vandforbrug
  show_states: true
  colorize_states: true
apex_config:
  xaxis:
    tickAmount: 12
    tickPlacement: between
    type: datetime
    labels:
      datetimeFormatter:
        year: yy
        month: MMM
        day: dd MMM
        hour: HH
    axisTicks:
      height: 6
all_series_config:
  show:
    legend_value: false
    datalabels: false
    extremas: true
    in_brush: false
  float_precision: 1
  type: area
  invert: false
yaxis:
  - decimals: 1
series:
  - entity: sensor.eforsyning_vand_water_exp_end
    type: line
    color: red
    name: Forventet forbrug
    data_generator: |
      return entity.attributes.data.map((start, index) => {
        return [new Date(start["date"]).getTime(), entity.attributes.data[index]["value"]];
      });
    group_by:
      duration: 1month
      func: sum
  - entity: sensor.eforsyning_vand_water_used
    type: column
    name: Forbrug
    data_generator: |
      return entity.attributes.data.map((start, index) => {
        return [new Date(start["date"]).getTime(), entity.attributes.data[index]["value"]];
      });
    group_by:
      duration: 1month
      func: sum
```

**Comment by danededane** [comment]
> you can do it with apexcharts. The important part is the **group by** in the series-section...
> 
> ```
> type: custom:apexcharts-card
> graph_span: 365d
> update_interval: 1d
> span:
>   end: day
> header:
>   show: true
>   title: Vandforbrug
>   show_states: true
>   colorize_states: true
> apex_config:
>   xaxis:
>     tickAmount: 12
>     tickPlacement: between
>     type: datetime
>     labels:
>       datetimeFormatter:
>         year: yy
>         month: MMM
>         day: dd MMM
>         hour: HH
>     axisTicks:
>       height: 6
> all_series_config:
>   show:
>     legend_value: false
>     datalabels: false
>     extremas: true
>     in_brush: false
>   float_precision: 1
>   type: area
>   invert: false
> yaxis:
>   - decimals: 1
> series:
>   - entity: sensor.eforsyning_vand_water_exp_end
>     type: line
>     color: red
>     name: Forventet forbrug
>     data_generator: |
>       return entity.attributes.data.map((start, index) => {
>         return [new Date(start["date"]).getTime(), entity.attributes.data[index]["value"]];
>       });
>     group_by:
>       duration: 1month
>       func: sum
>   - entity: sensor.eforsyning_vand_water_used
>     type: column
>     name: Forbrug
>     data_generator: |
>       return entity.attributes.data.map((start, index) => {
>         return [new Date(start["date"]).getTime(), entity.attributes.data[index]["value"]];
>       });
>     group_by:
>       duration: 1month
>       func: sum
> ```

Thanks @fuglphoenix , it looks very promising. 

Do you by any chance know how to make it show the current month also? and maybe begin with January? 😃 

![image](https://user-images.githubusercontent.com/9024493/202846450-73ef499f-8ccd-4a00-b9a0-00a01655ac1e.png)

**Comment by fuglphoenix** [comment]
```
span:
  end: year
```

**Comment by cvjensen** [comment]
> ```
> span:
>   end: year
> ```

Awesome thanks !

**Comment by danededane** [comment]
Awesome thanks !

**Comment by kpoppel** [comment]
I am adding this to the README as well.  thank-s for helping eachother out on this one.

**Comment by danededane** [comment]
All credits go to @fuglphoenix I'm just the one asking the stupid questions . 
Now all I need is a way to get the old data into HA's energy dashboard - thats a tricky one . 
If any of you got a solution let me know 😄

**Comment by kpoppel** [comment]
Actually I have attributed the code snippet to @fuglphoenix in the README too :-)

As for the historical data this is where Home Assistant is rather weak if you ask me.  I have contemplated the use of attributes (which holds all the nice historical data for Apexchart graphs) and looking towards the energy dashboard/graphs instead.
I did come across some vague documentation and another integration which looked like it "fixed up the past" so to speak.  However I haven't had time to look into this yet.
The trouble mainly comes from the fact that the HA database timestamps data by itself somewhere deep in the code.  There is no way someone can come with an integration and register say "tomorrow's electricity prices" or "yesterday's water usage" on the right day or hour.  For all real-time behaviour this is the perfect principle - for metering data coming through a data-hub 24 hours delayed it is a horrible behaviour.

**Comment by danededane** [comment]
> 

I just found [this](https://community.home-assistant.io/t/import-old-energy-readings-for-use-in-energy-dashboard/341406/27)
Guessing you already seen that. I get what you are saying - it seems a little sketchy . It's just so frustrating! Now I have water and electricity inside the energy tab , its only the heating that are missing 😠 Anyway I wanna thank you for this great integration!

**Comment by kpoppel** [comment]
Exactly that async statistics function is what I am looking at.  The direct SQL manipulation later in that thread is not a path for everybody and I recommend backing up data before doing it .-)
