### ISSUE TITLE
Feature request. Readings in MWh

### ISSUE THREAD

**Issue by Bluhme1** [kpoppel/homeassistant-eforsyning#43]
Just an idea. 
I am a big fan of your integration and use it for both heat and water. A great help in the quest to save energy - for the good of our spendings and our Planet.

Now time has come to get an overview of this years consumption. On the bill and on the eForsyning website the energy consumption is calculated in MWh, whereas the sensors created by your integration is in kWh.

Of course it is fairly easy to make a template toi change the values, but would it be an idea that the user could choose between getting the numbers in MWh or kwh?

And the data received from the API is in MWh as far as I can see

Wish you a Merry Christmas

Lars B

**Comment by kpoppel** [comment]
Yes, data is coming in as MWh.  Once HA only worked in kWh, so I changed it to this to be compatible.  Also for me personally kWh makes more sense as my house uses <50 kWh per day which makes all those decimals just a hassle.
Displaying totals in MWh though could be something.

**Comment by kpoppel** [comment]
In release v1.1.3 I made an update to the sensors with a "suggested unit of measurement" in MWh for all sensors except daily difference.  I just cannot figure out how that is used inside HA.  Numbers from the API driver is still reported in kWh as a common unit, but that should not hinder HA in converting it to MWh.

**Comment by Bluhme1** [comment]
Tried ver 1.1.3. Cannot find the "suggested unit of measurement" in the log.  Is it an attribute to the sensors?

**Comment by kpoppel** [comment]
Hmm, I need to double check as I don't recall seeing any warning on my test instance.
I am on the latest HA version which has this property for sensors:
https://github.com/kpoppel/homeassistant-eforsyning/blob/aad3ff54d409ebf546840fa28e085452f64400fb/custom_components/eforsyning/const.py#L113

**Comment by Bluhme1** [comment]
My latest data is from yesterday and I installed the new version yesterday. If data was fetched before the update, it might be the reason that I cannot see 'suggested_unit....'
Lets see tomorrow

**Comment by Bluhme1** [comment]
Tried again today. No success. There are no "suggested_unit...." in my sensors.

But doesn't really matter. As I can understand this feature needs a lot of work from you. It is rather easy to make templates that change the unit from kWh to MWh. So it is not worth it.

But thank you anyway

**Comment by kpoppel** [comment]
I get a little wiser every time I work on this integration, and at the same time Home Assistant is largely a moving target so every time something new appears.
Let's keep the issue open and I will keep it in mind whenever I make updates.

**Comment by kpoppel** [comment]
Good news!  Unit conversion is rolled out in the UI little by little, so template sensors for unit conversion should become a thing of the past.  On 2022.12.8 or later for instance, it is already there on the water and temperature sensor types:

![image](https://user-images.githubusercontent.com/4174578/211152803-9b5c8c5d-9627-4364-ac9f-46d6836617fc.png)

So this issue will solve itself.  2023.1 does not have it yet, let's see if 2023.2 does for energy sensors.

**Comment by Bluhme1** [comment]
You were right. Using beta 2023.2 and now it is possible to change unit fra kWh to kWh - and a lot of other things
Closing

Thanks
