### ISSUE TITLE
Water / Forsyning Comsumption for Energy Tab

### ISSUE THREAD

**Issue by kassoren** [kpoppel/homeassistant-eforsyning#44]
Hey again

Is it possible that you can configure the entities so they are able to add in the Energy tab?

Right now it says:
![water consump](https://user-images.githubusercontent.com/99141498/208697035-a2484d35-81ef-47f5-883c-fd2d8e1b3876.png)

And this links describes the issue:
https://www.home-assistant.io/more-info/statistics/

Thank you very much

**Comment by kpoppel** [comment]
Check out release v1.1.3 for this.

**Comment by kassoren** [comment]
Thanks 👍😎

**Comment by kpoppel** [comment]
If you think the update does what is expected, feel free to close the issue so I know all is well.

**Comment by kassoren** [comment]
I can add it to the energy tab now.. Just dont know yet which one i should add. But ill test some more.. thanks :)
