### ISSUE TITLE
Vandforbrug i november / december

### ISSUE THREAD

**Issue by Bluhme1** [kpoppel/homeassistant-eforsyning#45]
Jeg tager lige den på dansk, da det er for svært at forklare på engelsk (der er jo også nok kun danske brugere)

Årsafslutningen for vandforbrug er d. 31/10 og derfor lægges forbruget for november og december ind under 2023. Jeg har haft fat i Eforsyning og de forklarer at det er sådan det hænger sammen.

Men i min aflæsning via denne integration får jeg ikke data efter d. 31/10 - måske dukker de op for november og december 2022 d. 1/1, 2023, men så vil problemet genopstå i november og december 2023.

Det er en ikke særlige logisk måde at håndtere det på fra eForsynings side, men sådan er det altså.

Er der mulighed for at der kan tages højde for dette i integrationen?

@kpoppel . Du har tidligere skrevet at du ikke selv bruger eForsyning til vandaflæsning og derfor naturligvis har lidt svært ved at teste dette.
Jeg vedlægger det seneste dump fra min logfil, hvoraf det fremgår (i enden af denne) at den sidste aflæsning er 31/10

Vi har tidligere mailet sammen netop vedr. login muligheder for vandforsyningsdelen. Jeg gensender lige denne

/Lars B

[home-assistant_2022-12-21T09-42-28.516Z.log](https://github.com/kpoppel/homeassistant-eforsyning/files/10276615/home-assistant_2022-12-21T09-42-28.516Z.log)

**Comment by kpoppel** [comment]
Hej Lars

  Jeg er alligevel ved at rette et lille 'Nytårs-problem', så jeg ser på det, om der er noget jeg kan gøre.

**Comment by kpoppel** [comment]
Tjek release v1.1.2 Umiddelbart ser det ud til at løse denne.

**Comment by Bluhme1** [comment]
Ja. det ser sådan ud. Tak. Jeg lukker
