### ISSUE TITLE
Integration is using deprecated `DEVICE_CLASS_*` constants

### ISSUE THREAD

**Issue by frenck** [kpoppel/homeassistant-eforsyning#46]
This custom integration uses deprecated `DEVICE_CLASS_*` constants in its codebase.

The `DEVICE_CLASS_*` constants have been deprecated and replaced in Home Assistant Core 2021.12 (over a year ago). I would highly suggest updating/migrating this integration to the new enums.

For example, for the device classes supported by the `sensor` platform, there is now a `SensorDeviceClass` enum. So if a sensor previously used the `DEVICE_CLASS_ENERGY` constant, it should now use `SensorDeviceClass.ENERGY`. Other platforms (like `binary_sensor`, and `number`) provide similar enumerations for their supported device classes.

The migration thus only consists of replacing constants with an enumeration member and is, therefore, very low impact and should be fairly straightforward. I did noticed some have been migrated recently; however, there are still cases remaining in this repository (`sensor.py`).

If I can help resolve any questions regarding this change or migration, feel free to ask or respond to this issue. I'm happy to help!

Kindest regards,

../Frenck

**Comment by Stevens283** [comment]
Is this why Eforsyningen has stopped working?

**Comment by frenck** [comment]
If it stopped working, it wouldn't be because of this specific report/change.

**Comment by Stevens283** [comment]
> If it stopped working, it wouldn't be because of this specific report/change.

Oh, okay, I suddenly had all my Eforsyning Entities say unavailable, reloading was, of cause, ineffective, any ideas?

**Comment by frenck** [comment]
No, as said, not related to this issue, sorry 🤷

**Comment by kpoppel** [comment]
Thanks frenck.  This is a good help to stay updated.
Actually I just made a release of the integration where I made updates to the sensors to use the new enums, and try to use the "suggested_unit" attribute.  I'll take a look through the remaining code to catch left-overs.

**Comment by frenck** [comment]
@kpoppel It looks odd? Using some of those features you mentioned in your last comment, require a user to use minimal version of Home Assistant (e.g., `suggested_unit` was introduced fairly recently).

Yet, your `hacs.json` doesn't limit or guard a minimal Home Assistant version:
<https://github.com/kpoppel/homeassistant-eforsyning/blob/main/hacs.json>

**Comment by kpoppel** [comment]
Thanks for letting me know.  HA is really a moving target and as a 1%-time developer on this code it is not easy to stay on top :-)  I will read up o this aspect of Hacs too.

Actually if you don't mind I'd like to ask you  a question on this unit conversion?  The issue #43 requests the UI to show values in MWh.  The API returns values in kWh consistently, but there are some values which some find useful to be displayed in MWh.  I though the suggested_unit would enable some form of setting on the sensor to change the unit displayed, but that is not how this works I guess.  How would I go about this?
  I can ofc. scale everything from the API to be i MWh and some to be in kWh by disrupting historical data, but really I believe this should be a UI thing, not a base data unit thing.

**Comment by frenck** [comment]
>  but there are some values which some find useful to be displayed in MWh

Use can change the unit to anything they like in the entity setting themselves, Home Assistant will convert the units for them. If they like to show it in Wh, that is possible too 🤷 

>  I though the suggested_unit would enable some form of setting on the sensor to change the unit displayed, but that is not how this works I guess. 

That is not what that is. It suggest the unit Home Assistant should use for the sensor. This is only read the first time the sensor is created and added to the registries.

For example, 3D printers use degrees celsius for temperatures everywhere in the world. As Home Assistant will use Celsius or Fahrenheit for temperatures automatically based on the user settings. These 3D printer temperature sensors would previously end up being displayed as Farhenheit for our American users.

The suggested unit function, allows 3D printer integrations to say: Hey, whatever else, this sensor should be using Celcius. Home Assistant will honor this when creating the sensor. If a user decides he still want Farhenheit, the user can change it in the entity setting to override (and HA will again take care of conversion).

> The API returns values in kWh consistently

Then just publish them all as kWh. Don't go into converting them. Provide values as much as-is as possible. Users can override if they want or need it.

**Comment by kpoppel** [comment]
Ah okay.  I guess I will leave it in there so new installations will have MWh suggested... and set minimum HA version to 2022.12 where I think this first appeared? (I am looking through home-assistant/core to figure out when this actually was)

This entity setting for selecting the unit of display, where is that?  If i fx. go to one of the sensors it doesn't seem like the unit can be changed there?
![image](https://user-images.githubusercontent.com/4174578/211151217-b1fcb8b8-dd4c-4d5e-a544-cc1ee75183d7.png)

**Comment by frenck** [comment]
> This entity setting for selecting the unit of display, where is that? 

Right there on that screen. Is has been rolled out for many units already, but apparently not yet for energy. Should not take to long anymore, as every release new unit conversion have been added the past months.

../Frenck

**Comment by kpoppel** [comment]
Oh okay.  I will roll out 2023.1 on my test instance to see if it is there then.  That would solve that issue by itself then.
It is very friendly of you to help out with these questions. Thank-you.

**Comment by frenck** [comment]
> I will roll out 2023.1 on my test instance to see if it is there then.

It is not in 2023.1, just checked myself. Maybe 2023.2 🤷 

However, that does not change the way integration should handle thing. Integration should represent data as-is as much as possible.

> It is very friendly of you to help out with these questions. Thank-you.

Yeah, sure, no problem! 👍 

../Frenck

**Comment by frenck** [comment]
Thanks for address the original reported issue btw! Awesome!

../Frenck
