### ISSUE TITLE
Eforsyning stopped working in HA[BUG] 

### ISSUE THREAD

**Issue by Stevens283** [kpoppel/homeassistant-eforsyning#47]
This year suddenly all my Eforsyning Entities say unavailable, reloading was, of cause, ineffective
adding the Eforsyning from new, also did nothing.
When logging in to Eforsyning via webpage, everything works as normal, but HA isn't pulling any data

Any Idea on how to fix this?

## Log file output
This error originated from a custom integration.

Logger: custom_components.eforsyning.coordinator
Source: custom_components/eforsyning/coordinator.py:55
Integration: EForsyning (documentation, issues)
First occurred: 1 January 2023 at 01:41:08 (4604 occurrences)
Last logged: 10:18:46

Unexpected error fetching eForsyning data: 'IaltLinje'
Unexpected error fetching eForsyning data: 'NoneType' object is not subscriptable
Unexpected error fetching eForsyning data: HTTPSConnectionPool(host='apiapp.dff-edb.dk', port=443): Read timed out. (read timeout=5)
Unexpected error fetching eForsyning data: Invalid URL 'api/getebrugerinfo?id=': No scheme supplied. Perhaps you meant http://api/getebrugerinfo?id=?
Traceback (most recent call last):
  File "/config/custom_components/eforsyning/coordinator.py", line 53, in _async_update_data
    data = await self.hass.async_add_executor_job(self.api.get_latest)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 381, in get_latest
    result = self._parse_result_totals_line(year_data)
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 471, in _parse_result_totals_line
    'from-date': result['IaltLinje']['FraDatoStr'],
KeyError: 'IaltLinje'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/eforsyning/coordinator.py", line 55, in _async_update_data
    raise ConfigEntryNotReady from error
homeassistant.exceptions.ConfigEntryNotReady: 'IaltLinje'

**Comment by mm98** [comment]
Eforsyning is down. You can't login on [eforsyning.dk](eforsyning.dk) either. The mobile app `E|Forsyning` has the same problem. Looks like an required external `auth` resource (`apiapp.dff-edb.dk`) is down.

`Failure on HTTP request during access token aquisition: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

**Comment by Stevens283** [comment]
I updated, and All my problems were gone :)

**Comment by kpoppel** [comment]
I have logged some form of outage at eForsyning around
```2023-01-02 10:50:07.686 ERROR (MainThread) [custom_components.eforsyning.coordinator] Unexpected error fetching eForsyning data: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))```
It was gone 6 hours later for me though.
