### ISSUE TITLE
[BUG] Failed parsing result['IaltLinje']['FraDatoStr']

### ISSUE THREAD

**Issue by mm98** [kpoppel/homeassistant-eforsyning#58]
Please help me help you:

- [x] Describe what you experience and what the expectation was
- [x] Describe reproduction steps (if something special was done)
- [ ] Did you try to add the debug lines to configuration.yaml? Post the output please.
- [ ] If relevant, please post screenshots

## Describe the bug
I've updated `Eforsyning` to version `v1.2.3` and noticed that errors has started occuring in the HA logs. 
It looks like, [this](https://github.com/kpoppel/homeassistant-eforsyning/blob/2b168670eff0a778ed71b965bbe9202685f2ce54/custom_components/eforsyning/pyeforsyning/eforsyning.py#L541) line maybe is parsing something incorrect or the response was null (maybe?).

## To Reproduce
This happens automatically.

## Expected behavior
Ehhhmmm, not to throw an error? 😁

## Log file output
```
This error originated from a custom integration.

Logger: custom_components.eforsyning.coordinator
Source: custom_components/eforsyning/coordinator.py:55
Integration: EForsyning (documentation, issues)
First occurred: 21:47:12 (1 occurrences)
Last logged: 21:47:12

Unexpected error fetching eForsyning data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/config/custom_components/eforsyning/coordinator.py", line 53, in _async_update_data
    data = await self.hass.async_add_executor_job(self.api.get_latest)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 415, in get_latest
    result = self._parse_result_totals_line(year_data)
  File "/config/custom_components/eforsyning/pyeforsyning/eforsyning.py", line 541, in _parse_result_totals_line
    'from-date': result['IaltLinje']['FraDatoStr'],
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/eforsyning/coordinator.py", line 55, in _async_update_data
    raise ConfigEntryNotReady from error
homeassistant.exceptions.ConfigEntryNotReady: 'NoneType' object is not subscriptable
```

**Comment by kpoppel** [comment]
Thanks. Revert to 1.2.2 for now. I will check it out.

**Comment by kpoppel** [comment]
With Home Assistant 2023.2.3 and then latest version installed I cannot reproduce this error.  Looking at the place in the code it would seem data retrieved was not as expected.  This could be a temporary API error.

**Comment by mm98** [comment]
I haven't seen this error since. So i'll close this issue.
