### ISSUE TITLE
Data opdateres kun ved genstart

### ISSUE THREAD

**Issue by jenslauridsen** [kpoppel/homeassistant-eforsyning#59]
Hej

Det er først og fremmest en super god integration i eforsyning og det hele fungerede perfekt ved opsætningen. Jeg undrer mig bare lidt over at der ikke kommer nye data ind, men fandt ud af at den henter alt hvis jeg genstarter HA. Er der en mulighed for at få integrationen til at forespørge data hver dag eller er der noget jeg mangler at sætte op?

Her er mit nuværende dashboard med data:
![image](https://user-images.githubusercontent.com/94701584/233318082-f38d2f9e-07d3-4ee5-a9b2-cb4962131084.png)

Med venlig hilsen
Jens

**Comment by kpoppel** [comment]
Hej Jens

Integrationen skulle meget gerne hente data hver dag uden yderligere opsætning. F.eks.:
![image](https://user-images.githubusercontent.com/4174578/234398086-92c3fa47-133a-4b95-8b0a-98b749fc956b.png)

Tjek evt. loggen for fejlmeddelelser fra integrationen.  Jeg kører seneste Home Assistant version uden problemer af denne slags.

**Comment by jenslauridsen** [comment]
Hej

Jeg tror at fejlen var relateret til forsinkede værdier fra eforsyning + apexcharts-card som var sat til kun at bliver reloaded 1 gang i døgnet. Jeg har set i logs efter fejl men mon ikke alt er ok.

Beklager forstyrrelsen fra min side.

**Comment by kpoppel** [comment]
Ja, jeg har hørt nogle kan have data forsinket i 2-3 dage hvis fjernaflæsningen er ustabil eller hvis man bor et sted hvor der skal en forbi med en radio for at aflæse målerne.

Jeg lukker dette issue så.
