### ISSUE TITLE
"Submit" greyed out in "Add Integration"

### ISSUE THREAD

**Issue by jolsso** [kpoppel/homeassistant-eforsyning#6]
This is definitely a minor thing, which I assume could be Home Assistant specific.

When adding the integration in "Add Integration" under "Integrations": the "Submit" button is greyed out until you select/de-select the "Billing July to June?" checkbox.

**Comment by kpoppel** [comment]
Yes, I saw this also.  I have no idea how to fix this, but welcome a merge request which fixes it.  Even if it just improving the documentation on this point.

**Comment by kpoppel** [comment]
Fixed on main now.
