### ISSUE TITLE
Ingen værdier i entiteter

### ISSUE THREAD

**Issue by Lyngaae** [kpoppel/homeassistant-eforsyning#60]
Jeg har fulgt guiden efter bedste evne og tilføjet integrationen. Jeg er dog lidt i tvivl om mit supplier ID er korrekt, men den godkender det og indlæser integrationen. (har prøvet med andre ID's der fejler)

Jeg får indlæst 20 entiteter fra eForsyningen men de er alle med status "ukendt" selv efter et par dage. Jeg er sikker på at din integration ikke fejler noget, men at jeg gør noget forkert et sted :)

**Comment by MartinNorgaardDK** [comment]
Har samme udfordring.

**Comment by wilsky** [comment]
Hej Lyngaae og MartinNorgaardDK. Jeg havde samme problem med at der ikke var nogen synlige data efter opsætning. Jeg havde forsøgt login med e-mailadresse og password. Da jeg i stedet brugte mit forbrugernummer og 4-cifret kode fra en af fakturaerne, så kom der data igennem med det samme.

**Comment by kpoppel** [comment]
Integrationen er ikke testet med email og password, så jeg ved ikke om det følger en anden vej til login. Men forbrugernummer og 4-cifret kode er det der er udgangspunktet.

**Comment by Lyngaae** [comment]
Perfekt, virkede. Skal bare lige finde ud af hvilken entity der skal anvendes til Energi dashboard :D

**Comment by MartinNorgaardDK** [comment]
Jeg bruger mit forbrugernummer og webpinkode, men får desværre stadig ikke nogen værdier ind.
![Skærmbillede 2023-10-23 125835](https://github.com/kpoppel/homeassistant-eforsyning/assets/111115533/ea1318d9-8998-466e-8693-b272a016b5da)

**Comment by kpoppel** [comment]
Hej @MartinNorgaardDK .  Har du set på logfilen hvad den siger?  Hvis du ser i README, kan du se hvad du skal sætte ind i configuration.yml for at aktivere logging.

**Comment by 123322212** [comment]
Hej kpoppel, jeg har prøvet at lave integrationen, men møder denne i debug: 2024-02-23 13:58:45.591 ERROR (MainThread) [custom_components.eforsyning.coordinator] Unexpected error fetching eForsyning data: HTTPSConnectionPool(host='apiapp.dff-edb.dk', port=443): Read timed out. (read timeout=5) Har du nogen ide? og fedt at du har lavet integrationen.

**Comment by kpoppel** [comment]
Tak for anerkendelsen 😊 Hmm, den fejl kommer ofte når apiapp.dff-edb.dk ikke kan kontaktes. Som regel er det forbipasserende. Jeg kan i min egen log se, at jeg havde noget ligende d. 20.2. Prøv og se om det er forbigående. Hvis ikke kan det være du måske er kommet på et nyere Api. Man ved jo aldrig.

**Comment by MathiasReker** [comment]
Please see: https://github.com/kpoppel/homeassistant-eforsyning/pull/62

**Comment by kpoppel** [comment]
Ny release her: https://github.com/kpoppel/homeassistant-eforsyning/releases/tag/v1.2.5
