### ISSUE TITLE
[INFO] eforsyning.dk SSL certificate expired (external problem)

### ISSUE THREAD

**Issue by mm98** [kpoppel/homeassistant-eforsyning#70]
## Describe the bug
I'm creating this issue, so you won't get multiple bug reports for an external error. The SSL certificate has expired on https://eforsyning.dk/. Which causes this integration to fail (as it should).

**Comment by Bluhme1** [comment]
Is there anything we can do about it?

**Comment by mm98** [comment]
> Is there anything we can do about it?

They (www.dff-edb.dk / www.softvaerket.dk) will probably see it tomorrow. The SSL certificate expired the 30th. Which is on a  day off (weekend).

**Comment by kpoppel** [comment]
Thanks for the info, much appreciated.

**Comment by mm98** [comment]
SSL certificate has been updated. Integration works again.
